-- SRT Santena Racing Team - Supabase schema
-- Eseguire nel SQL Editor di Supabase.

create extension if not exists pgcrypto;

create type public.user_role as enum ('admin', 'driver');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role public.user_role not null default 'driver',
  driver_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  year integer not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#e10600',
  logo text,
  country text not null default 'Italia',
  created_at timestamptz not null default now()
);

create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  surname text not null default '',
  number integer not null,
  nationality text not null default 'Italia',
  team_id bigint references public.teams(id) on delete set null,
  platform text not null default 'Crossplay',
  avatar text,
  color text not null default '#e10600',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(number)
);

alter table public.profiles
  drop constraint if exists profiles_driver_id_fkey;
alter table public.profiles
  add constraint profiles_driver_id_fkey foreign key (driver_id)
  references public.drivers(id) on delete set null;

create table if not exists public.races (
  id bigint generated by default as identity primary key,
  season_id bigint references public.seasons(id) on delete cascade,
  round integer not null,
  name text not null,
  circuit text not null,
  country text not null,
  race_date date not null,
  race_time time,
  status text not null default 'upcoming' check (status in ('upcoming','live','completed')),
  laps integer,
  created_at timestamptz not null default now(),
  unique(season_id, round)
);

create table if not exists public.race_results (
  id bigint generated by default as identity primary key,
  race_id bigint not null references public.races(id) on delete cascade,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  position integer,
  points numeric(6,2) not null default 0,
  grid_position integer,
  pole boolean not null default false,
  fastest_lap boolean not null default false,
  dnf boolean not null default false,
  penalty_seconds numeric(6,2) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  unique(race_id, driver_id)
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Annuncio',
  excerpt text,
  content text,
  image text,
  author text not null default 'Admin',
  published_at timestamptz not null default now()
);

create table if not exists public.scoring_settings (
  id bigint generated by default as identity primary key,
  season_id bigint not null unique references public.seasons(id) on delete cascade,
  position_points jsonb not null default '[25,18,15,12,10,8,6,5,4,3,2,1]'::jsonb,
  pole_bonus numeric(5,2) not null default 1,
  fastest_lap_bonus numeric(5,2) not null default 1,
  attendance_bonus numeric(5,2) not null default 0
);

-- Crea automaticamente il profilo dopo la registrazione.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), 'driver');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.seasons enable row level security;
alter table public.teams enable row level security;
alter table public.drivers enable row level security;
alter table public.races enable row level security;
alter table public.race_results enable row level security;
alter table public.news enable row level security;
alter table public.scoring_settings enable row level security;

-- Lettura pubblica dei dati del campionato.
create policy "public read seasons" on public.seasons for select using (true);
create policy "public read teams" on public.teams for select using (true);
create policy "public read drivers" on public.drivers for select using (true);
create policy "public read races" on public.races for select using (true);
create policy "public read results" on public.race_results for select using (true);
create policy "public read news" on public.news for select using (true);
create policy "public read scoring" on public.scoring_settings for select using (true);

-- Ogni utente autenticato può leggere il proprio profilo; l'admin tutti.
create policy "read own profile or admin" on public.profiles for select
using (auth.uid() = id or public.is_admin());
create policy "update own profile" on public.profiles for update
using (auth.uid() = id) with check (auth.uid() = id);

-- Solo l'admin può modificare i dati del campionato.
create policy "admin manage seasons" on public.seasons for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage teams" on public.teams for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage drivers" on public.drivers for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage races" on public.races for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage results" on public.race_results for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage news" on public.news for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage scoring" on public.scoring_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "admin manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

insert into public.seasons (name, year, is_active)
select 'Season 1', 2026, true
where not exists (select 1 from public.seasons);


-- Il primo utente registrato diventa Admin; i successivi restano Piloti.
create or replace function public.bootstrap_first_admin()
returns boolean
language plpgsql
security definer set search_path = public
as $$
declare
  admin_exists boolean;
begin
  if auth.uid() is null then return false; end if;
  select exists(select 1 from public.profiles where role = 'admin') into admin_exists;
  if not admin_exists then
    update public.profiles set role = 'admin' where id = auth.uid();
    return true;
  end if;
  return false;
end;
$$;
grant execute on function public.bootstrap_first_admin() to authenticated;

-- Dati iniziali minimi. Puoi modificarli dal pannello Admin nelle versioni successive.
insert into public.teams (name, color, country)
select * from (values
 ('Ferrari', '#e8002d', 'Italia'),
 ('Red Bull Racing', '#3671c6', 'Austria'),
 ('Mercedes', '#27f4d2', 'Germania'),
 ('McLaren', '#ff8000', 'Regno Unito')
) as v(name,color,country)
where not exists (select 1 from public.teams);
